// Framework-agnostic types shared across main, preload, and renderer.
//
// No Electron or Node runtime imports here so the renderer bundle stays
// sandbox-safe.

// --- Metric snapshots -------------------------------------------------------

// A single local metric reading, null-safe for temperature.
export interface MetricsSnapshot {
  source: 'local';
  timestamp: number; // Date.now() at collection
  cpuLoadPercent: number; // 0..100, rounded for display in UI
  memTotalBytes: number; // raw bytes from si.mem().total
  memUsedBytes: number; // active RAM, excluding reclaimable cache
  cpuTempC: number | null; // null => render "N/A"
  error: string | null; // non-null when a tick failed; UI shows error badge
}

export type RemoteConnectionState =
  | 'idle' // no active profile selected
  | 'connecting' // first connect in progress
  | 'connected' // ready, polling
  | 'reconnecting' // dropped, backoff retry loop active
  | 'error'; // unrecoverable auth/host error (test surface)

export interface RemoteMetricsSnapshot {
  source: 'remote';
  profileId: string | null; // which profile produced this; null when idle
  connectionState: RemoteConnectionState;
  timestamp: number;
  cpuLoadPercent: number | null; // null while connecting/reconnecting
  memTotalBytes: number | null;
  memUsedBytes: number | null;
  cpuTempC: number | null; // null => "N/A"
  error: string | null; // descriptive error string for UI
}

// --- SSH profiles -----------------------------------------------------------

// Persisted shape (includes id; password plain text per MVP).
export interface SshProfile {
  id: string; // stable uuid, generated by main on first save
  name: string; // user-facing label
  host: string;
  port: number; // defaults to 22 when omitted on input
  username: string;
  password: string; // PLAIN TEXT in MVP (accepted gap; Phase 2 = safeStorage)
}

// Input from the renderer form. id absent => create; present => update in place.
export interface SshProfileInput {
  id?: string;
  name: string;
  host: string;
  port?: number; // normalized to 22 in main when missing/invalid
  username: string;
  password: string;
}

export interface SshTestResult {
  ok: boolean;
  error?: string; // descriptive string when ok === false
}

// --- Preload-exposed API (the only renderer surface) ------------------------

export interface MonitorApi {
  // push subscriptions; return an unsubscribe fn
  onMetricsLocal(cb: (s: MetricsSnapshot) => void): () => void;
  onMetricsRemote(cb: (s: RemoteMetricsSnapshot) => void): () => void;

  // request/response
  testConnection(input: SshProfileInput): Promise<SshTestResult>;
  saveProfile(input: SshProfileInput): Promise<SshProfile>;
  deleteProfile(id: string): Promise<{ ok: boolean }>;
  listProfiles(): Promise<SshProfile[]>;

  // fire-and-forget
  selectProfile(id: string | null): void;
  minimizeWindow(): void;
  closeApp(): void;
  openPrivacySettings(): void;
}
